#!/bin/sh

case $1 in
   config)
        cat <<'EOM'
graph_title DVS garbage collection
graph_vlabel GC acties per ${graph_period}
graph_args --base 1000
graph_scale no
graph_category rdt-dvs
graph_info Aantal GC acties
graph_period minute
gc_trein.label trein store
gc_trein.info Aantal GC acties in trein store
gc_trein.type DERIVE
gc_trein.min 0
gc_trein.colour aa1300
gc_station.label station store
gc_station.info Aantal GC acties in station store
gc_station.type DERIVE
gc_station.min 0
gc_station.colour 9300aa

EOM
        exit 0;;
esac

printf "gc_trein.value "
/opt/rdt/infoplus-dvs/dvs-dump.py count/gc_trein -q -l
printf "gc_station.value "
/opt/rdt/infoplus-dvs/dvs-dump.py count/gc_station -q -l
