#!/bin/sh

case $1 in
   config)
        cat <<'EOM'
graph_title Aantal DVS injecties
graph_vlabel injecties per ${graph_period}
graph_args --base 1000
graph_scale no
graph_category rdt-dvs
graph_info Aantal verwerkte DVS injecties
graph_period minute
injecties.label injecties
injecties.info Aantal injecties
injecties.type DERIVE
injecties.min 0

EOM
        exit 0;;
esac

printf "injecties.value "
/opt/rdt/infoplus-dvs/dvs-dump.py count/injecties -q
