#!/bin/sh

case $1 in
   config)
        cat <<'EOM'
graph_title Aantal DVS berichten
graph_vlabel berichten per ${graph_period}
graph_args --base 1000
graph_scale no
graph_category rdt-dvs
graph_info Aantal verwerkte DVS berichten
berichten.label berichten
berichten.info Aantal berichten
berichten.type DERIVE
berichten.min 0
EOM
        exit 0;;
esac

printf "berichten.value "
/opt/rdt/infoplus-dvs/dvs-dump.py count/msg -q -l
