#!/bin/sh

case $1 in
   config)
        cat <<'EOM'
graph_title Aantal DVS fouten
graph_vlabel berichten per ${graph_period}
graph_args --base 1000
graph_scale no
graph_category rdt-dvs
graph_info Aantal verwerkte DVS berichten
graph_period minute
berichten_ouder.label verouderd
berichten_ouder.info Aantal verouderde (niet verwerkte) berichten
berichten_ouder.type DERIVE
berichten_ouder.min 0
berichten_ouder.colour aa1300
berichten_dubbel.label dubbel
berichten_dubbel.info Aantal dubbele berichten
berichten_dubbel.type DERIVE
berichten_dubbel.min 0
berichten_dubbel.colour 9300aa
berichten_laat.colour aa1300
berichten_laat.label te laat
berichten_laat.info Aantal te late berichten
berichten_laat.type DERIVE
berichten_laat.min 0
berichten_laat.colour ff8000

EOM
        exit 0;;
esac

printf "berichten_ouder.value "
/opt/rdt/infoplus-dvs/dvs-dump.py count/ouder -q
printf "berichten_dubbel.value "
/opt/rdt/infoplus-dvs/dvs-dump.py count/dubbel -q
printf "berichten_laat.value "
/opt/rdt/infoplus-dvs/dvs-dump.py count/laat -q
